### ISSUE TITLE
Can't connect to daemon

### ISSUE THREAD

**Issue by DamienCassou** [syncthing/syncthing-gtk#107]
Hi,

syncthing daemon `v0.10.26` is listening and can be accessed through http://127.0.0.1:8080/. However, when I launch syncthing-gtk, in the GUI I get "Connecting to Syncthing daemon at http://127.0.0.1:8081..." (note the different port) and nothing happens. In the terminal, I get:

```
(syncthing-gtk:17240): Gdk-WARNING **: The GDK_NATIVE_WINDOWS environment variable is not supported in GTK3.
See the documentation for gdk_window_ensure_native() on how to get native windows.
ERROR:root:Could not find any typelib for Notify

(syncthing-gtk:17240): Gtk-WARNING **: No object called: edit-menu-button-image

(syncthing-gtk:17240): Gtk-WARNING **: No object called: edit-menu-button-image
E:Daemon:Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/nix/store/yshmd0njhfrixckhyspxh5wrgcaq0p9j-python2.7-syncthing-gtk-0.6.2/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 380, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
E:Daemon:Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/nix/store/yshmd0njhfrixckhyspxh5wrgcaq0p9j-python2.7-syncthing-gtk-0.6.2/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 380, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
E:Daemon:Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/nix/store/yshmd0njhfrixckhyspxh5wrgcaq0p9j-python2.7-syncthing-gtk-0.6.2/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 380, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
E:Daemon:Could not connect to 127.0.0.1: Connection refused
[...]
```

**Comment by kozec** [comment]
WebUI address is read from syncthing configuration file (`~/.config/syncthing/config.xml`) What do you have under \<gui\> node?

**Comment by DamienCassou** [comment]
kozec writes:

> WebUI address is read from syncthing configuration file (`~/.config/syncthing/config.xml`) What do you have under \<gui\> node?

I changed it from `8081` to `8080` and things are now working fine,
thank you. It is strange however that the web UI was actually listening
on `8080` and not `8081`...

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
