### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_filename' on Ubuntu 14.04

### ISSUE THREAD

**Issue by degenkolb** [syncthing/syncthing-gtk#127]
Hi

after including https://launchpad.net/~ytvwld/+archive/ubuntu/syncthing and https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/ with add-apt-repository I installed syncthing and syncthing-gtk and tried to start syncthing-gtk but got the following exception and an empty window. 

Versions:
syncthing (0.10.30-3)
syncthing-gtk (0.6.4-1~webupd8~trusty0)

The OS is a Kubuntu (Ubuntu 14.04.2 LTS)

```
~$ syncthing-gtk 

(syncthing-gtk:5924): Gtk-WARNING **: No object called: edit-menu-button-image

(syncthing-gtk:5924): Gtk-WARNING **: No object called: edit-menu-button-image
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 114, in do_startup
    self.setup_statusicon()
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 292, in setup_statusicon
    self.statusicon = get_status_icon(self.iconpath, self["si-menu"])
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py", line 571, in get_status_icon
    return StatusIconProxy(*args)
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py", line 484, in __init__
    self._load_fallback()
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py", line 517, in _load_fallback
    self._status_fb = StatusIconBackend(*self._arguments)
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py", line 410, in __init__
    self._kde_menu = self._get_popupmenu()
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py", line 372, in _get_popupmenu
    menu_qt.addAction(self._make_qt_action(menu_child_gtk, menu_qt))
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py", line 311, in _make_qt_action
    set_image()
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py", line 307, in set_image
    action.setIcon(self._get_icon_by_name(icon_name))
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py", line 339, in _get_icon_by_name
    icon_path = self._gtk_icon_theme.lookup_icon(icon_name, 48, 0).get_filename()
AttributeError: 'NoneType' object has no attribute 'get_filename'
```

For a screenshot see http://imgur.com/2vSL9c6

Did I miss something?

**Comment by kozec** [comment]
@alexander255 are you still around, by any chance?

Anyway, it looks like you either have no GTK icon theme installed or you are using one without icons that nobody expected to be missing...

**Comment by alexander255** [comment]
I'll look into it, but I guess the assertion that every theme icon used by the status menu actually exists in the current GTK icon theme doesn't hold (interestingly this never happend to me during testing; and I also tested on Kubuntu 14.04...).

**Comment by kozec** [comment]
@alexander255 It's probably OK to not display missing icons, but not crashing on them :)

**Comment by alexander255** [comment]
Hi @degenkolb!
Please test if this works before we commit it to master:

1. Make sure Syncthing-GTK is closed
2. Open a Terminal
3. Run this command to download my GIT repository: `git clone https://github.com/alexander255/syncthing-gtk.git`
4. Enter `cd syncthing-gtk` to open the downloaded GIT repository folder
5. Type `./syncthing-gtk.py` to run Syncthing-GTK and make sure it works as expected

Please also paste the output of the last command here (it will probably contain some lines similar to this: `I StatusIcon    Skipping unknown icon file: go-down`).

Finally please re-run Syncthing-GTK like this and check if any additional icons are displayed in the status icon menu that were missing using the original command from above: `SYNCTHING_STATUS_BACKEND=GTK3 ./syncthing-gtk.py`

Thank you for your help in getting this fixed!

**Comment by degenkolb** [comment]
Hi

the requested output from `./syncthing-gtk.py` is the following.
Also now a setup wizard opens. After completing the wizard is see the following screenshot http://i.imgur.com/tzSBlLv.png (There are still 3 icons missing. The two upper right and one on the right side of the usage report)

```
~/src/syncthing-gtk$ ./syncthing-gtk.py                      

(syncthing-gtk.py:3206): Gtk-WARNING **: No object called: edit-menu-button-image

(syncthing-gtk.py:3206): Gtk-WARNING **: No object called: edit-menu-button-image
I StatusIcon    Skipping unknown icon file: gtk-about
I StatusIcon    Skipping unknown icon file: gtk-quit
W StatusIcon    StatusIcon: Using backend StatusIconKDE4 (fallback)
I Wizard        Searching for syncthing binary...
I Wizard         ... ./syncthing
I Wizard         ... ./syncthing.x64
I Wizard         ... /home/degenkolb/.local/bin/syncthing
I Wizard         ... /home/degenkolb/.local/bin/syncthing.x64
I Wizard         ... /home/degenkolb/.config/syncthing/syncthing
I Wizard         ... /home/degenkolb/.config/syncthing/syncthing.x64
I Wizard         ... /opt/mpi/bin/syncthing
I Wizard         ... /opt/mpi/bin/syncthing.x64
I Wizard         ... /opt/intel/composer_xe_2011_sp1.9.293/bin/intel64/syncthing
I Wizard         ... /opt/intel/composer_xe_2011_sp1.9.293/bin/intel64/syncthing.x64
I Wizard         ... /usr/local/sbin/syncthing
I Wizard         ... /usr/local/sbin/syncthing.x64
I Wizard         ... /usr/local/bin/syncthing
I Wizard         ... /usr/local/bin/syncthing.x64
I Wizard         ... /usr/sbin/syncthing
I Wizard         ... /usr/sbin/syncthing.x64
I Wizard         ... /usr/bin/syncthing
I Wizard        Binary found in /usr/bin/syncthing
I DaemonProcess Subprocess finished with code 0
I Wizard        syncthing-gtk: Configuration directory: '/home/degenkolb/.config/syncthing'
I Wizard        syncthing-gtk: Syncthing configuration directory: /home/degenkolb/.config/syncthing
I Wizard        17:15:02 INFO: Generating RSA key and certificate for syncthing...
I Wizard        17:15:07 INFO: Device ID: O66V4GB-ZK3XBSE-Q44PCCL-SWP7KTN-MXTHI4E-JCXLTJB-26E64WX-S56N6QP
I DaemonProcess Subprocess finished with code 0
I Wizard        syncthing-gtk: chosen port 8080
E Daemon        Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/home/degenkolb/src/syncthing-gtk/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
E Daemon        Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/home/degenkolb/src/syncthing-gtk/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
E Daemon        Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/home/degenkolb/src/syncthing-gtk/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
E Daemon        Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/home/degenkolb/src/syncthing-gtk/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
E Daemon        Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/home/degenkolb/src/syncthing-gtk/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
E Daemon        Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/home/degenkolb/src/syncthing-gtk/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
E Daemon        Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/home/degenkolb/src/syncthing-gtk/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
I App           updatecheck: disabled
```

If I close this `syncthing-gtk` and restart it with `SYNCTHING_STATUS_BACKEND=GTK3 ./syncthing-gtk.py` I get the following output.
The programm window is the same as in the screenshot from above.

```
~/src/syncthing-gtk$ SYNCTHING_STATUS_BACKEND=GTK3 ./syncthing-gtk.py

(syncthing-gtk.py:3476): Gtk-WARNING **: No object called: edit-menu-button-image

(syncthing-gtk.py:3476): Gtk-WARNING **: No object called: edit-menu-button-image
I StatusIcon    StatusIcon: Using requested backend StatusIconGTK3
E Daemon        Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/home/degenkolb/src/syncthing-gtk/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
E Daemon        Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/home/degenkolb/src/syncthing-gtk/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
E Daemon        Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/home/degenkolb/src/syncthing-gtk/syncthing_gtk/daemon.py", line 391, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
I App           updatecheck: disabled
```

Let me know if you need more output and thanks for the work.

**Comment by kozec** [comment]
Two of those three missing icons are "x" and "system-emblem-symbolic", I'm not quite sure what's icon doing there :D

Anyway, displaying them without theme that provides them is problem. "x" button is created by gtk, so I have no saying in what icon is used. Symbolic can be replaced on runtime, but I'd guess that when one of base icons is missing, rest is probably not there as well.

So, not crashing is probably sufficient solution here, and I'll check if is possible to declare "any gtk icon theme" as dependency in Ubuntu.

**Comment by alexander255** [comment]
KDE menu will be missing the icons for the "Info" and "Quit" items, but considering the current state of his GTK theme that seems like a good solution... 

@degenkolb Thanks for testing!
Could please try this (tested this on KDE 5 so the instructions might vary a bit):

1. Open the KDE Systemsettings
2. Go to *Common Appearance and Behavior* -> *Application Appearance* -> *GNOME-Applikationstyle (GTK)* 
3. Select a different icon theme in the *Icon Themes* section
4. Click *Apply*
5. Try running Syncthing-GTK again

If you are unable to select any icon themes then that's the actual problem, install the package `gnome-icon-theme` and try again.
