### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by apastuszak** [syncthing/syncthing-gtk#141]
I went into directory containing the source and ran "sudo python setup.py install" and watched syncthing-gtk install.

When I run syncthing-gtk from the command line I get this display:

```
Traceback (most recent call last):
  File "/usr/bin/syncthing-gtk", line 14, in <module>
    from syncthing_gtk.tools import init_logging
  File "/usr/lib/python3.4/site-packages/syncthing_gtk/__init__.py", line 2, in <module>
    import tools
ImportError: No module named 'tools'
```
If I stay in the directory that contains the syncthing install and run syncthing-gtk.py it launches fine.

If I try to run syncthing-gtk.py from another directory by pathing to it, I get this:

```
File "/home/andy/Downloads/syncthing-gtk-master/syncthing_gtk/app.py", line 114, in do_startup
    self.setup_widgets()
  File "/home/andy/Downloads/syncthing-gtk-master/syncthing_gtk/app.py", line 269, in setup_widgets
    self.builder.add_from_file(os.path.join(self.gladepath, "app.glade"))
  File "/home/andy/Downloads/syncthing-gtk-master/syncthing_gtk/uibuilder.py", line 31, in add_from_file
    self.add_from_string(file(filename, "r").read())
IOError: [Errno 2] No such file or directory: u'./app.glade'
```

Any ideas?

**Comment by kozec** [comment]
For start, use python 2 (ideally 2.7). I'm not sure where tools.py gone, but I'm pretty sure that py3 can't handle ST-GTK and that may be what's causing the problem.

**Comment by apastuszak** [comment]
Yep, Arch.  I'll give it a test.

**Comment by kozec** [comment]
Ok, I guess this was caused by Arch's famous python3-as-default bug...
