### ISSUE TITLE
[DEBIAN] syncthing-gtk.py doesn't save UI settings

### ISSUE THREAD

**Issue by Booteille** [syncthing/syncthing-gtk#176]
Hi.

I tried to save the UI settings and nothing happened. Here are logs displayed in the console after I click on the "save" button.
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/editordialog.py", line 335, in cb_btSave_clicked
    self.on_save_reuqested()
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/uisettingsdialog.py", line 176, in on_save_reuqested
    self.store_values(VALUES)
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/editordialog.py", line 356, in store_values
    self.store_value(key, widget)
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/uisettingsdialog.py", line 142, in store_value
    return EditorDialog.store_value(self, key, w)
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/editordialog.py", line 371, in store_value
    self.set_value(strip_v(key), w.get_active())
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/uisettingsdialog.py", line 147, in set_value
    set_run_on_startup(value, "Syncthing-GTK", get_executable(),
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/tools.py", line 351, in get_executable
    executable = os.path.normpath(os.path.join(os.getcwd(), executable))
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
```

**Comment by kozec** [comment]
Is there anything you are trying to save with diacritical marks or other non-ascii characters? 'Syncthing binary location' on 'Advanced' page would be good candidate for that.
