### ISSUE TITLE
GUI fails to load

### ISSUE THREAD

**Issue by danheidel** [syncthing/syncthing-gtk#201]
I'm trying to run syncthing-gtk on Mint 17.  The application GUI loads an empty window with no UI elements in it.  This appears to be a separate issue from the other UI load failures reported here.

Fresh install from the PPA, running the latest version of syncthing.  

Starting the app from the command line, I get the following output: 

```
I StatusIcon    Using backend StatusIconGTK3 (primary)

(syncthing-gtk:16177): Gtk-WARNING **: Invalid icon size 16


(syncthing-gtk:16177): Gtk-WARNING **: Invalid icon size 16

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 841, in cb_syncthing_device_added
    used
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 1306, in show_device
    box.set_dark_color(*self.dark_color)
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/infobox.py", line 417, in set_dark_color
    la = self.grid.child_get_property(w, "left-attach")
TypeError: child_get_property() takes exactly 4 arguments (3 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 841, in cb_syncthing_device_added
    used
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 1306, in show_device
    box.set_dark_color(*self.dark_color)
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/infobox.py", line 417, in set_dark_color
    la = self.grid.child_get_property(w, "left-attach")
TypeError: child_get_property() takes exactly 4 arguments (3 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 841, in cb_syncthing_device_added
    used
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 1306, in show_device
    box.set_dark_color(*self.dark_color)
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/infobox.py", line 417, in set_dark_color
    la = self.grid.child_get_property(w, "left-attach")
TypeError: child_get_property() takes exactly 4 arguments (3 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 841, in cb_syncthing_device_added
    used
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 1306, in show_device
    box.set_dark_color(*self.dark_color)
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/infobox.py", line 417, in set_dark_color
    la = self.grid.child_get_property(w, "left-attach")
TypeError: child_get_property() takes exactly 4 arguments (3 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 841, in cb_syncthing_device_added
    used
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 1306, in show_device
    box.set_dark_color(*self.dark_color)
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/infobox.py", line 417, in set_dark_color
    la = self.grid.child_get_property(w, "left-attach")
TypeError: child_get_property() takes exactly 4 arguments (3 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 908, in cb_syncthing_folder_added
    [ self.devices[n["deviceID"]] for n in r["devices"] ],
KeyError: u'DQU5SOL-3UWAXGH-2MGBSZO-J6B7MWU-5TEEZQ6-IZFLUW3-S22K5UK-FESXAQB'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 908, in cb_syncthing_folder_added
    [ self.devices[n["deviceID"]] for n in r["devices"] ],
KeyError: u'DQU5SOL-3UWAXGH-2MGBSZO-J6B7MWU-5TEEZQ6-IZFLUW3-S22K5UK-FESXAQB'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 908, in cb_syncthing_folder_added
    [ self.devices[n["deviceID"]] for n in r["devices"] ],
KeyError: u'DQU5SOL-3UWAXGH-2MGBSZO-J6B7MWU-5TEEZQ6-IZFLUW3-S22K5UK-FESXAQB'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 908, in cb_syncthing_folder_added
    [ self.devices[n["deviceID"]] for n in r["devices"] ],
KeyError: u'DQU5SOL-3UWAXGH-2MGBSZO-J6B7MWU-5TEEZQ6-IZFLUW3-S22K5UK-FESXAQB'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 908, in cb_syncthing_folder_added
    [ self.devices[n["deviceID"]] for n in r["devices"] ],
KeyError: u'DQU5SOL-3UWAXGH-2MGBSZO-J6B7MWU-5TEEZQ6-IZFLUW3-S22K5UK-FESXAQB'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 908, in cb_syncthing_folder_added
    [ self.devices[n["deviceID"]] for n in r["devices"] ],
KeyError: u'DQU5SOL-3UWAXGH-2MGBSZO-J6B7MWU-5TEEZQ6-IZFLUW3-S22K5UK-FESXAQB'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 908, in cb_syncthing_folder_added
    [ self.devices[n["deviceID"]] for n in r["devices"] ],
KeyError: u'DQU5SOL-3UWAXGH-2MGBSZO-J6B7MWU-5TEEZQ6-IZFLUW3-S22K5UK-FESXAQB'
```

**Comment by kozec** [comment]
Sorry, I had to edit that to get something readable... That bug is really weird, because missing argument for `child_get_property` is supposed to be optional, but this should fix it.

**Comment by danheidel** [comment]
I tried this fix but now I'm getting 
    TypeError: Argument 3 does not allow None as a value
errors

**Comment by kozec** [comment]
Looks like it's time to upgrade my Mint VM... Linux Mint 17.3, I guess?

**Comment by danheidel** [comment]
I'm running 17.1 but 17.2 or 17.3 is probably a better choice.

**Comment by kozec** [comment]
Soooo... Wow. It turns out that Mint 17.3 uses GTK 3.10.
That may be why it is affected by 3 years old bug: https://bugzilla.gnome.org/show_bug.cgi?id=685076

Trying what can be done...
