### ISSUE TITLE
TypeError on Windows

### ISSUE THREAD

**Issue by daniele-athome** [syncthing/syncthing-gtk#225]
Using version 0.8.0.0.1 on Windows 7.

```
I StatusIcon    Using backend StatusIconGTK3 (primary)
Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\app.py", line 118, in do_startup
  File "c:\syncthing-gui\syncthing_gtk\app.py", line 321, in setup_connection
  File "c:\syncthing-gui\syncthing_gtk\app.py", line 369, in show_wizard
  File "c:\syncthing-gui\syncthing_gtk\wizard.py", line 62, in __init__
  File "c:\syncthing-gui\syncthing_gtk\wizard.py", line 181, in __init__
  File "c:\syncthing-gui\syncthing_gtk\wizard.py", line 470, in init_page
TypeError: bad operand type for unary +: 'unicode'
```

After that, an empty tray icon is created and the main window is empty. Any action on any menu has no effect.

![syncthing-gtk-win32](https://cloud.githubusercontent.com/assets/3763726/11711213/0b577e00-9f25-11e5-8bf8-b04ddcb2f391.PNG)

I have a system-wide Python 2.5 installation on Windows, but I see that Syncthing-GTK has its own 2.7 stuff.

**Comment by kozec** [comment]
> Using version 0.8.0.0.1

How? :D

Anyway, do you have accented or other non-ascii character in your home directory path?

**Comment by daniele-athome** [comment]
No I don't: C:\Users\[username]; username is a combination of plain letters and numbers.

**Comment by daniele-athome** [comment]
I think it has been fixed in master:
https://github.com/syncthing/syncthing-gtk/blob/v0.8.0.0.1/syncthing_gtk/wizard.py#L469

```
self.label = WrappedLabel(
	"<b>" + _("Syncthing is generating RSA key and certificate.") + "</b"> +
	"\n\n" +
	_("This may take a while...")
)
```

That HTML tag is uncorrectly closed (the close tag sign is outside the string).
I think we can close this. Sorry I didn't check/try the latest code.
