### ISSUE TITLE
About window does not appear

### ISSUE THREAD

**Issue by daniele-athome** [syncthing/syncthing-gtk#228]
When clicking on the About menu item:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 1563, in cb_about
    AboutDialog(self, self.gladepath).show(self["window"])
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/aboutdialog.py", line 16, in __init__
    self.setup_widgets(app)
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/aboutdialog.py", line 34, in setup_widgets
    self.builder.add_from_file(os.path.join(self.gladepath, "about.glade"))
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 40, in add_from_file
    self.add_from_string(file(filename, "r").read())
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 45, in add_from_string
    self._build()
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 104, in _build
    self._find_translatables()
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 124, in _find_translatables
    self._find_translatables(child)
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 122, in _find_translatables
    self._translate(child)
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/uibuilder.py", line 129, in _translate
    child.nodeValue = _(child.nodeValue)
  File "/usr/local/lib/python2.7/dist-packages/syncthing_gtk/tools.py", line 52, in <lambda>
    _ = lambda (a) : gettext.gettext(a).decode("utf-8")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 8: ordinal not in range(128)
```

I thought it was a locale issue, but even starting it with LANG=C caused the same error.
Tried with v0.8.1 on Debian GNU/Linux, latest testing channel.

**Comment by kozec** [comment]
Is rest of interface in English? What locale are you using normally?

**Comment by daniele-athome** [comment]
Yes, UI is always in English. My system locale is `it_IT.utf8`.

**Comment by daniele-athome** [comment]
Thanks! I'll try it tomorrow.
