### ISSUE TITLE
KeyError: u'time' in /daemon.py", line 756, in _syncthing_cb_errors

### ISSUE THREAD

**Issue by muelli** [syncthing/syncthing-gtk#229]
I receive this stacktrace when running syncthing-gtk:
```
Traceback (most recent call last):
  File "/var/tmp/st-gtk/local/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 484, in _rest_response
    callback(rdata)
  File "/var/tmp/st-gtk/local/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 756, in _syncthing_cb_errors
    t = parsetime(e["time"])
KeyError: u'time'
```

**Comment by kozec** [comment]
That should be harmless. Is there any error displayed or skipped in window?

**Comment by muelli** [comment]
nope.   I don't notice anything in the UI.  Everything seems to work fine.  I just thought I file the bug, because whenever I see stacktraces, I think there is a bug somewhere...

**Comment by kozec** [comment]
Yeah, that's good idea. I should probably make check there so it doesn't scare users :)
