### ISSUE TITLE
Time parsing failing in Nautilus plugin

### ISSUE THREAD

**Issue by jpts** [syncthing/syncthing-gtk#233]
When running nautilus I get the following trace. This is preventing the plugin working at all :(

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 484, in _rest_response
    callback(rdata)
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 729, in _init_event_pooling
    self._last_error_time = datetime.datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 484, in _rest_response
    callback(rdata)
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 834, in _syncthing_cb_last_seen
    t = parsetime(data[nid]["lastSeen"])
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/tools.py", line 161, in parsetime
    raise ValueError("Failed to parse '%s' as time" % m)
ValueError: Failed to parse '2015-12-23T11:03:28.225929682Z' as time
```

nautilus v3.18.3
syncthing  v0.12.8
syncthing-gtk v0.8.1

**Comment by jpts** [comment]
Ah, I lied slightly, I was on v0.8.0.1 and have just updated to v0.8.1, fixing it being completely broken. I do however, still get the traceback above.

**Comment by kozec** [comment]
Well, '2015-12-23T11:03:28.225929682Z' really is not time st-gtk can parse. What localization, language and time zone are you using?

**Comment by jpts** [comment]
Timezone: Europe/London
Lang: en_GB.utf8

**Comment by kozec** [comment]
So, timezone zero. I can see how that can be a problem...

**Comment by AudriusButkevicius** [comment]
2015-12-23T11:03:28.225929682Z is a perfectly valid zulu timestamp.
