### ISSUE TITLE
[0.9.0.1] Right click-> Edit on Folders not working

### ISSUE THREAD

**Issue by noidexe** [syncthing/syncthing-gtk#270]
When I do Right Click-> Edit on a folder nothing happens. The other options (edit ignore patters, rescan, browser, etc) work just fine. 

I also get an error saying "Joining Relay Session (BEP/relay): Incorrect response code 1: not found" and the option "Display Syncthing-inotify Output" is greyed out. Not sure if the errors are related or not. 

I tested this on one computer running windows 10. None of the errors have appeared on a second computer running windows 7

**Comment by kozec** [comment]
'Display Syncthing-inotify Output' grayed out probably means you don't have inotify enabled on any folder.

Can you try to run syncthing-gtk-console.exe on that W10 machine? It's in same directory as regular exe is and displays error message(s) that may show cause of that missing window.

**Comment by noidexe** [comment]
I tried right click-> edit but it didn't seem to generate any output

```
C:\Program Files (x86)\SyncthingGTK\library.zip\syncthing_gtk\windows.py:11: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
C:\Program Files (x86)\SyncthingGTK\library.zip\syncthing_gtk\infobox.py:8: PyGIWarning: Rsvg was imported without specifying a version first. Use gi.require_version('Rsvg', '2.0') before import to ensure that the right version gets loaded.
I StatusIcon    Using backend StatusIconGTK3 (primary)
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)
Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\daemon.py", line 409, in _rest_connected
Error: g-io-error-quark: Could not connect to 127.0.0.1: No connection could be made because the target machine actively refused it. (39)
I App           updatecheck: too soon
W Daemon        Unhandled event type: {u'data': {u'wan': [{u'RawQuery': u'', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'0.0.0.0:22000', u'User': None, u'Path': u'', u'Scheme': u'tcp'}, {u'RawQuery': u'', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'186.137.129.115:13306', u'User': None, u'Path': u'', u'Scheme': u'tcp'}], u'lan': [{u'RawQuery': u'', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'0.0.0.0:22000', u'User': None, u'Path': u'', u'Scheme': u'tcp'}], u'address': {u'RawQuery': u'', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'0.0.0.0:22000', u'User': None, u'Path': u'', u'Scheme': u'tcp'}}, u'type': u'ListenAddressesChanged', u'id': 40, u'time': u'2016-05-20T09:36:38.518792-03:00'}
W Daemon        Unhandled event type: {u'data': {u'wan': [{u'RawQuery': u'id=53STGR7-YBM6FCX-PAZ2RHM-YPY6OEJ-WYHVZO7-PCKQRCK-PZLTP7T-434XCAD&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=2000000&globalLimitBps=2500000&statusAddr=:22070&providedBy=canton7', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'23.92.71.120:443', u'User': None, u'Path': u'/', u'Scheme': u'relay'}], u'lan': [{u'RawQuery': u'id=53STGR7-YBM6FCX-PAZ2RHM-YPY6OEJ-WYHVZO7-PCKQRCK-PZLTP7T-434XCAD&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=2000000&globalLimitBps=2500000&statusAddr=:22070&providedBy=canton7', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'23.92.71.120:443', u'User': None, u'Path': u'/', u'Scheme': u'relay'}], u'address': {u'RawQuery': u'', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'relays.syncthing.net', u'User': None, u'Path': u'/endpoint', u'Scheme': u'dynamic+https'}}, u'type': u'ListenAddressesChanged', u'id': 5261, u'time': u'2016-05-20T09:36:47.200152-03:00'}
W Daemon        Unhandled event type: {u'data': {u'wan': [{u'RawQuery': u'id=4DPTHBY-G6Y5CDI-2HH2ZUI-674CQUG-IYTPVZ7-CRRJMPH-7A5ELMO-4WM5SQS&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'162.243.201.102:22067', u'User': None, u'Path': u'/', u'Scheme': u'relay'}], u'lan': [{u'RawQuery': u'id=4DPTHBY-G6Y5CDI-2HH2ZUI-674CQUG-IYTPVZ7-CRRJMPH-7A5ELMO-4WM5SQS&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'162.243.201.102:22067', u'User': None, u'Path': u'/', u'Scheme': u'relay'}], u'address': {u'RawQuery': u'', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'relays.syncthing.net', u'User': None, u'Path': u'/endpoint', u'Scheme': u'dynamic+https'}}, u'type': u'ListenAddressesChanged', u'id': 5302, u'time': u'2016-05-20T09:36:57.202186-03:00'}

(syncthing-gtk-console.exe:11112): Gtk-WARNING **: Could not find the icon 'folder-open-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(syncthing-gtk-console.exe:11112): Gtk-WARNING **: Error loading theme icon 'media-playback-pause' for stock: Icon 'media-playback-pause' not present in theme Adwaita
Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\app.py", line 1703, in cb_menu_popup_edit_folder
  File "c:\syncthing-gui\syncthing_gtk\app.py", line 1802, in open_editor
  File "c:\syncthing-gui\syncthing_gtk\foldereditor.py", line 31, in __init__
  File "c:\syncthing-gui\syncthing_gtk\editordialog.py", line 57, in __init__
AttributeError: 'Notebook' object has no attribute 'pack_start'
Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\app.py", line 1703, in cb_menu_popup_edit_folder
  File "c:\syncthing-gui\syncthing_gtk\app.py", line 1802, in open_editor
  File "c:\syncthing-gui\syncthing_gtk\foldereditor.py", line 31, in __init__
  File "c:\syncthing-gui\syncthing_gtk\editordialog.py", line 57, in __init__
AttributeError: 'Notebook' object has no attribute 'pack_start'
I App           Opening 'http://127.0.0.1:8384' in browser
I App           Joining relay session (BEP/relay): read tcp 192.168.0.102:62962->162.243.201.102:22067: i/o timeout

**Comment by kozec** [comment]
```
Traceback (most recent call last):
  File "c:\syncthing-gui\syncthing_gtk\app.py", line 1703, in cb_menu_popup_edit_folder
  File "c:\syncthing-gui\syncthing_gtk\app.py", line 1802, in open_editor
  File "c:\syncthing-gui\syncthing_gtk\foldereditor.py", line 31, in __init__
  File "c:\syncthing-gui\syncthing_gtk\editordialog.py", line 57, in __init__
AttributeError: 'Notebook' object has no attribute 'pack_start'
```

Is probably error that I'm looking for, but fixing it may take some time as it doesn't show up on any of mine machines :(

**Comment by kozec** [comment]
Actually, that code is part of code that handles small screens... Can I ask what resolution are you using?

**Comment by noidexe** [comment]
1366x768

**Comment by kozec** [comment]
Now testing this will be funny part :)

**Comment by kozec** [comment]
@noidexe , can you try [this build](https://github.com/syncthing/syncthing-gtk/files/275570/SyncthingGTK-v0.9.0.1-1-g714bf90-win32-full-installer.exe.zip) ?

**Comment by noidexe** [comment]
Everything's working fine know :100: 
Right -> Edit works fine and now that I'm able to enable filesystem monitoring "Display inotify output" is no longer greyed out.

**Comment by koldKat** [comment]
I second that, now it works. Had the same problems.
Thank you :+1:

**Comment by kozec** [comment]
Thanks for confirmation.

Fix included in [latest release](https://github.com/syncthing/syncthing-gtk/releases/latest)
