### ISSUE TITLE
Folders missing in the ui

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-gtk#283]
Hi

I cloned the latest version and started running it. ALl the devices are listed buit the ui is missing the list of the shared folders. The left side is literally empty. I have my folders listed properly in the web ui.

I am using it on Debian Testing. And I am using the latestversion of syncthing

**Comment by kozec** [comment]
Would it be possible to copy-paste output of 
`syncthing-gtk -d` ?

**Comment by kozec** [comment]
*bump*

Also, distro, number of bits and Syncthing version would be helpful.

**Comment by gerroon** [comment]
distro is Debian testing and using whatever the latest syncthing is atm ( I am not around of that pc atm)

**Comment by cmacmackin** [comment]
I've encountered this issue too. I'm running Linux Mint 17.3 Cinnamon 64-bit with Syncthing-GTK v0.7.6 and Daemon v0.13.10. I got the following output from running `syncthing-gtk -d`:

```
D UIBuilder     Enabled: traditional_header
D UIBuilder     Enabled: old_gtk
D UIBuilder     Enabled: icons_in_menu
D UIBuilder     Loading glade file /usr/share/syncthing-gtk/app.glade
D UIBuilder     Enabled conditions: set([u'old_gtk', u'icons_in_menu', u'traditional_header'])
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node !is_gnome | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: !old_gtk
D UIBuilder     Removed 'child' by attribute: header_bar
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'child' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node traditional_header
D UIBuilder     Allowed node traditional_header | icons_in_menu
I StatusIcon    Using backend StatusIconGTK3 (primary)
V Notifications Error notifications enabled
V Notifications File update notifications enabled

Syncthing-GTK started and running in notification area
V Daemon        Set refresh interval to 5
E Daemon        Could not connect to 127.0.0.1: Connection refused
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 387, in _rest_connected
    con = sc.connect_to_service_finish(results)
GError: Could not connect to 127.0.0.1: Connection refused
D App           Creating connect_dialog
V App           Settinig connect_dialog label Starting Syncth
D InfoBox       hex state changed to Disconnected
D InfoBox       Phone state changed to Disconnected
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 915, in cb_syncthing_folder_added
    r["readOnly"], r["ignorePerms"], 
KeyError: u'readOnly'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 915, in cb_syncthing_folder_added
    r["readOnly"], r["ignorePerms"], 
KeyError: u'readOnly'
D InfoBox       hex state changed to Connected
D InfoBox       hex state changed to 
I App           updatecheck: disabled
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 469, in _rest_response
    callback(rdata)
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 739, in _syncthing_cb_errors
    for e in errors["errors"]:
TypeError: 'NoneType' object is not iterable
D InfoBox       Phone state changed to Connected
D InfoBox       Phone state changed to Disconnected
D InfoBox       Phone state changed to Connected
D InfoBox       Phone state changed to Up to Date
W Daemon        Unhandled event type: {u'data': {u'wan': [{u'RawQuery': u'id=DKJ3IJT-IUDHKNK-2DW5YJJ-JSXV5MN-JGMNLD7-JVPOKHH-HHRPR5Y-3Z3IUQQ&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=Jusque: Somewhere in Illinois', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'199.175.53.85:22067', u'User': None, u'Path': u'/', u'Scheme': u'relay'}], u'lan': [{u'RawQuery': u'id=DKJ3IJT-IUDHKNK-2DW5YJJ-JSXV5MN-JGMNLD7-JVPOKHH-HHRPR5Y-3Z3IUQQ&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=Jusque: Somewhere in Illinois', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'199.175.53.85:22067', u'User': None, u'Path': u'/', u'Scheme': u'relay'}], u'address': {u'RawQuery': u'', u'Opaque': u'', u'RawPath': u'', u'Fragment': u'', u'Host': u'relays.syncthing.net', u'User': None, u'Path': u'/endpoint', u'Scheme': u'dynamic+https'}}, u'type': u'ListenAddressesChanged', u'id': 46, u'globalID': 46, u'time': u'2016-07-17T23:14:24.025646621-03:00'}
```

I am trying to sync with my Android phone, running v0.13.7 of Syncthing. This has two folders, one containing music and the other pictures. The music one is set as master on my computer, while the pictures one is set as master on my phone. I am using inotify for both and have set the scan intervals of both folders on my computer to be hourly. I have a list of ignore patterns for the music.

**Comment by kozec** [comment]
> Syncthing-GTK v0.7.6 and Daemon v0.13.10.

That's not gonna work, Syncthing-GTK v0.7.* can't talk with Syncthing v0.13 or newer due to REST API changes. Updating to latest Syncthing-GTK should help.

**Comment by cmacmackin** [comment]
Okay, thanks for that information. It seemed that some of my package sources were broken, so the UI hadn't been upgraded in a while.
