### ISSUE TITLE
gir1.2-notify should be added as a dependency

### ISSUE THREAD

**Issue by licaon-kter** [syncthing/syncthing-gtk#292]
At least on Debian, 0.9.1, it won't start without it, even if the notification settings are not checked:

```
** (syncthing-gtk:16701): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Traceback (most recent call last):
  File "/usr/bin/syncthing-gtk", line 26, in <module>
    from syncthing_gtk.tools import init_logging, init_locale
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/__init__.py", line 15, in <module>
    from notifications          import Notifications, HAS_DESKTOP_NOTIFY
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/notifications.py", line 19, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

**Comment by kozec** [comment]
@hotice could you, please, check if this is not problem with your Ubuntu packages as well?

**Comment by hotice** [comment]
Thanks for the mention. I'll update the package in a few minutes!

**Comment by kozec** [comment]
Great, thanks.
