### ISSUE TITLE
Error while launching SyncThing-GTK 0.9.2 Windows 10

### ISSUE THREAD

**Issue by TurBoss** [syncthing/syncthing-gtk#309]
Hi
I'm trying to install syncthing but when i run the shorcut a popup wiht this apears
```
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "scripts/syncthing-gtk-exe.py", line 40, in <module>
  File "c:\syncthing-gui\syncthing_gtk\configuration.py", line 192, in Configuration
  File "c:\syncthing-gui\syncthing_gtk\windows.py", line 224, in WinConfiguration
  File "c:\syncthing-gui\syncthing_gtk\configuration.py", line 72, in __init__
  File "c:\syncthing-gui\syncthing_gtk\configuration.py", line 112, in check_values
AttributeError: 'Logger' object has no attribute 'verbose'
```

any ideas ?

thx!

**Comment by robsonsobral** [comment]
A friend of mine is having the same issue.

It looks like the directories `c:\syncthing-gui\` and `c:\Python27` aren't being created.

**Comment by kozec** [comment]
Those paths are irrelevant, stored from build machine. I already have idea how to fix this, but I'd love to know what's causing it first :(

**Comment by kozec** [comment]
Can anyone with that problem, please, test this version?

[SyncthingGTK-v0.9.2.1-win32-full-installer.exe.zip](https://github.com/syncthing/syncthing-gtk/files/441654/SyncthingGTK-v0.9.2.1-win32-full-installer.exe.zip)

**Comment by tonirug** [comment]
v0.9.2.1 works fine for me on W10.
Thanks!

**Comment by kozec** [comment]
@tonirug Thanks for confirmation, I pronounced it [officially latest](https://github.com/syncthing/syncthing-gtk/releases/tag/v0.9.2.1) release :)

**Comment by TurBoss** [comment]
Works fine thank you

**Comment by seiferflo** [comment]
0.9.2.1 solve the problem, thanks @kozec
