### ISSUE TITLE
IndexError: list index out of range in foldereditor.py in line 159 in on_data_loaded

### ISSUE THREAD

**Issue by muelli** [syncthing/syncthing-gtk#402]
I've just installed st-gtk from git and get this error after having shared folders with my newly running instance:

```
Traceback (most recent call last):
  File "/var/tmp/st-gtk/local/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 525, in _rest_response
    callback(rdata)
  File "/var/tmp/st-gtk/local/lib/python2.7/site-packages/syncthing_gtk/editordialog.py", line 213, in cb_data_loaded
    if self.on_data_loaded():
  File "/var/tmp/st-gtk/local/lib/python2.7/site-packages/syncthing_gtk/foldereditor.py", line 159, in on_data_loaded
    self.values = [ x for x in self.config["folders"] if x["id"] == self.id ][0]
IndexError: list index out of range
```

Then the app freezes and I can't do anything with the app any more.
![screenshot from 2017-10-14 13-53-02](https://user-images.githubusercontent.com/322807/31575428-06a55f32-b0e7-11e7-9997-540da3b509d5.png)

**Comment by kozec** [comment]
Weird, that would mean you are trying to edit folder with ID that's not in config file. What have you clicked to get there?

**Comment by muelli** [comment]
Hrm. I didn't click much.
It was a fresh instance.  Maybe the changes to the config file didn't reflect timely enough?
