### ISSUE TITLE
syncthing-gtk.exe and it's child rundll32.exe keeps run after I exits application

### ISSUE THREAD

**Issue by TrueXakeP** [syncthing/syncthing-gtk#425]
I do exit from tray icon. Icon disappear, window closes but this two processes keeps run. Sometimes syncthing-gtk.exe keeps run alone.

Syncthing-GTK 0.9.3 and 0.9.2.7
Windows 8.1 Enterprise x64

**Comment by kozec** [comment]
I'm afraid this may be bug in Gio (GTK) which may be problematic, as they don't support Windows officially.

How problem it means? Does that rundll32.exe exits evenutaly?

**Comment by TrueXakeP** [comment]
When I restart syncthing-gtk several times and then close it I see this:
![screen](https://user-images.githubusercontent.com/5345528/36629702-5a9acde6-1962-11e8-932e-735c585971be.png)
One rundll32.exe and several syncthing-gtk.exe. They only eat memory. And I do not know how this affects the syncthing-gtk itself.

**Comment by kozec** [comment]
There is syncthing-gtk-console.exe installed right next to regular exe. If you run it from command line, it will display logs and errors. Please, try exiting ST-GTK started like that and check if there is anything interesting printed out.

**Comment by TrueXakeP** [comment]
I'll check this in a few days, sorry.

**Comment by TrueXakeP** [comment]
When I do quit from -console.exe the log just stops. Py version exits normally instead.

Got this log with -console.exe (and broken connect in v0.9.3; after that -console.exe remains running but silent):
```
I StatusIcon    Using backend StatusIconGTK3 (primary)
I App
I App           Syncthing-GTK started and running in notification area
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\daemon.py", line 1149, in _response
TypeError: 'NoneType' object is not iterable
I App           updatecheck: disabled
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\daemon.py", line 1149, in _response
TypeError: 'NoneType' object is not iterable
I App           updatecheck: disabled
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\daemon.py", line 1149, in _response
TypeError: 'NoneType' object is not iterable
I App           updatecheck: disabled
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\daemon.py", line 1149, in _response
TypeError: 'NoneType' object is not iterable
I App           updatecheck: disabled
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\daemon.py", line 1149, in _response
TypeError: 'NoneType' object is not iterable
I App           updatecheck: disabled
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\daemon.py", line 1149, in _response
TypeError: 'NoneType' object is not iterable
I App           updatecheck: disabled
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\daemon.py", line 1149, in _response
TypeError: 'NoneType' object is not iterable
I App           updatecheck: disabled
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\daemon.py", line 1149, in _response
TypeError: 'NoneType' object is not iterable
I App           updatecheck: disabled
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\daemon.py", line 1149, in _response
TypeError: 'NoneType' object is not iterable
I App           updatecheck: disabled
```

But this with py version:
```
C:\Python27\python.exe C:/Users/root/Projects/syncthing-gtk/syncthing-gtk.py
I StatusIcon    Using backend StatusIconGTK3 (primary)
I App           
I App           Syncthing-GTK started and running in notification area
I App           updatecheck: disabled

Process finished with exit code 0
```
