### ISSUE TITLE
App still unresponsive

### ISSUE THREAD

**Issue by jtojnar** [syncthing/syncthing-gtk#428]
After update to 0.9.3, I tried removing `~/.config/syncthing{,-gtk}` but the app still freezes on starting Syncthing daemon – cannot even click Quit.

![image](https://user-images.githubusercontent.com/705123/36625200-6eaef1e6-191b-11e8-8d7a-d7f49d787b7e.png)

```
W Configuration Failed to load configuration; Creating new one.
W Configuration Reason: (IOError(2, 'No such file or directory'),)
D UIBuilder     Enabled: header_bar
D UIBuilder     Enabled: is_gnome
D UIBuilder     Enabled: icons_in_menu
D UIBuilder     Loading glade file /nix/store/czvpna3wm40lvi393kcz9n3741xgrsjj-syncthing-gtk-0.9.3/share/syncthing-gtk/app.glade
D UIBuilder     Enabled conditions: set([u'icons_in_menu', u'is_gnome', u'header_bar'])
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed node !is_gnome | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'child' by attribute: traditional_header
D UIBuilder     Removed 'child' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed node traditional_header
D UIBuilder     Allowed node traditional_header | icons_in_menu
I StatusIcon    Using backend StatusIconGTK3 (primary)
D Daemon        Reading syncthing config /home/jtojnar/.config/syncthing/config.xml

(.syncthing-gtk-wrapped:20878): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
I Wizard        syncthing-gtk: Configuration directory: '/home/jtojnar/.config/syncthing'
I Wizard        syncthing-gtk: Syncthing configuration directory: /home/jtojnar/.config/syncthing
I Wizard        04:15:07 INFO: Device ID: Z2TIVR3-L3JBVNA-N4P27HB-JBCLF57-DNSB5PM-TH3CRSM-2G6JNSD-44AL2QQ
I Wizard        04:15:07 INFO: Default folder created and/or linked to new config
I DaemonProcess Subprocess finished with code 0
I Wizard        syncthing-gtk: chosen port 8080
D Wizard        Generated apikey 81jugk3rbteshm0ouomkvcxmf9wqlc
D Daemon        Reading syncthing config /home/jtojnar/.config/syncthing/config.xml
V Notifications Error notifications enabled
V Notifications File update notifications enabled
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Traceback (most recent call last):
  File "/nix/store/czvpna3wm40lvi393kcz9n3741xgrsjj-syncthing-gtk-0.9.3/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 1050, in _connected
    self._connection = self.connect_to_service_finish(results)
Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
D App           Creating connect_dialog
V App           Settinig connect_dialog label Starting Syncth
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Traceback (most recent call last):
  File "/nix/store/czvpna3wm40lvi393kcz9n3741xgrsjj-syncthing-gtk-0.9.3/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 1050, in _connected
    self._connection = self.connect_to_service_finish(results)
Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Traceback (most recent call last):
  File "/nix/store/czvpna3wm40lvi393kcz9n3741xgrsjj-syncthing-gtk-0.9.3/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 1050, in _connected
    self._connection = self.connect_to_service_finish(results)
Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
D InfoBox       kaiser state changed to Disconnected
/nix/store/98bghm0wfyh6ygvr0yg6slyl5xnnj5hs-python2.7-pygobject-3.26.1/lib/python2.7/site-packages/gi/module.py:176: Warning: cannot register existing type 'RsvgHandle'
  g_type = info.get_g_type()
/nix/store/98bghm0wfyh6ygvr0yg6slyl5xnnj5hs-python2.7-pygobject-3.26.1/lib/python2.7/site-packages/gi/module.py:176: Warning: g_once_init_leave: assertion 'result != 0' failed
  g_type = info.get_g_type()
/nix/store/98bghm0wfyh6ygvr0yg6slyl5xnnj5hs-python2.7-pygobject-3.26.1/lib/python2.7/site-packages/gi/module.py:210: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  type_ = g_type.pytype
/nix/store/98bghm0wfyh6ygvr0yg6slyl5xnnj5hs-python2.7-pygobject-3.26.1/lib/python2.7/site-packages/gi/module.py:224: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  g_type.pytype = wrapper
/nix/store/98bghm0wfyh6ygvr0yg6slyl5xnnj5hs-python2.7-pygobject-3.26.1/lib/python2.7/site-packages/gi/module.py:224: Warning: g_type_set_qdata: assertion 'node != NULL' failed
  g_type.pytype = wrapper
```

**Comment by jtojnar** [comment]
Opened an issue about the pygobject warnings: https://gitlab.gnome.org/GNOME/librsvg/issues/210

**Comment by kozec** [comment]
> Warning: cannot register existing type 'RsvgHandle'

This sounds important. Do you have librsvg and gobject-introspection bindings installed? Both should be in `librsvg` package, but it may wary by distro.

**Comment by jtojnar** [comment]
Yes, I do. Without it the error woold be `ValueError: Namespace Rsvg not available`

**Comment by kozec** [comment]
Nothing else seems to be missing from that log, but not being able to render svgs sounds like good reason to not being able to draw anything or even freeze.

Did v0.9.2.7 displayed same thing

**Comment by jtojnar** [comment]
Yes, it did.

**Comment by kozec** [comment]
Ok, I'll be honest here, I've tried to install NixOS into Virtualbox and noticed two things:

1. v0.9.2.7 does _not_ display that rsvg message for me and
2. i have no idea how to install python packages there in way that I can use them from git checkout there :D

**Comment by jtojnar** [comment]
2. Usually, you would write `shell.nix` and then run `nix-shell` but you can create ad-hoc shells like `nix-shell -p python2 python2Packages.pygobject3 gtk` or even `nix-shell -A syncthing-gtk` to use the dependencies listed in the distribution.

Maybe this is desktop environment dependent. I will try it in the appliance as well as other VMs.

**Comment by kozec** [comment]
So, after running from last checkout and under...

```
nix-shell -p python2 python2Packages.pygobject3 gtk3 '(librsvg.override { enableIntrospection = true; })' python2Packages.dateutil syncthing psmisc
```

... I was able to get GUI working with following patch:

<details>

```patch
diff --git a/syncthing_gtk/infobox.py b/syncthing_gtk/infobox.py
index c5f3b19..37d3550 100644
--- a/syncthing_gtk/infobox.py
+++ b/syncthing_gtk/infobox.py
@@ -465,6 +465,7 @@ class InfoBox(Gtk.Container):
 	def _prepare_icon(self, icon):
 		if icon.endswith(".svg"):
 			# Icon is svg file
+			return Gtk.Image.new_from_icon_name('info', 16)
 			key = icon if self.dark_color is None else icon + "-dark"
 			if not key in svg_cache:
 				if not self.dark_color is None:
diff --git a/syncthing_gtk/app.py b/syncthing_gtk/app.py
index 10feb6a..b0ff5dc 100644
--- a/syncthing_gtk/app.py
+++ b/syncthing_gtk/app.py
@@ -229,9 +229,9 @@ class App(Gtk.Application, TimerManager):
 			if not self.daemon is None:
 				self.daemon.set_refresh_interval(REFRESH_INTERVAL_TRAY)
 		else:
-			if self.wizard is None:
+			if self.wizard is None and not self.is_visible():
 				# Show main window
-				self.cb_statusicon_click()
+				self.show()
 		self.hide_window = False
 	
 	def setup_commandline(self):
diff --git a/syncthing_gtk/notifications.py b/syncthing_gtk/notifications.py
index 21b96a5..46c2739 100644
--- a/syncthing_gtk/notifications.py
+++ b/syncthing_gtk/notifications.py
@@ -19,7 +19,7 @@ try:
 		gi.require_version('Notify', '0.7')
 		from gi.repository import Notify
 		HAS_DESKTOP_NOTIFY = True
-except ImportError:
+except (ValueError, ImportError):
 	pass
 
 if HAS_DESKTOP_NOTIFY:
```
</details>

It disables drawing SVG and I kinda hope you'd have better idea why that helps as I do right now :)

Continuing to investigate in meantime.

**Comment by jtojnar** [comment]
Great, can confirm that https://github.com/syncthing/syncthing-gtk/commit/011c235913730485149960a1a36dd2afd119a4d8 works, I can do without the icons for now. I have no understanding of what the problem is, except that it seems to be some kind of deadlock. Hopefully upstream will be able to tell us something this week https://gitlab.gnome.org/GNOME/librsvg/issues/210

**Comment by jtojnar** [comment]
Apparently, it was caused by two different instances of librsvg used at the same time.

With https://github.com/NixOS/nixpkgs/commit/47d0a11a60c18a396f5fec8d36f9a88ca5dd9198, syncthing-gtk was freezing, but when I cherry-picked https://github.com/NixOS/nixpkgs/commit/0c2ede96a07c0bcef90c772558f922efc035437c onto it, it started working.

Thanks to @lazka for [pointing me in the right direction](https://gitlab.gnome.org/GNOME/librsvg/issues/210#note_104773).
