### ISSUE TITLE
Don't update syncthing on windows server 2003

### ISSUE THREAD

**Issue by SofroN** [syncthing/syncthing-gtk#440]
When you first start after installation, the program cannot check for an update.
```
c:\Program Files\SyncthingGTK>syncthing-gtk-console.exe
I StatusIcon    Using backend StatusIconGTK3 (primary)
I Wizard        Searching for syncthing binary...
I Wizard         ... ./syncthing.exe
I Wizard         ... C:\Documents and Settings\admin/.local/bin\syncthing.exe
I Wizard         ... C:\Documents and Settings\admin\Local Settings\Application
Data\syncthing\syncthing.exe
I Wizard         ... c:/Program Files/syncthing\syncthing.exe
I Wizard         ... c:/Program Files (x86)/syncthing\syncthing.exe
I Wizard         ... C:\Documents and Settings\admin\Local Settings\Application
Data\syncthing\syncthing.exe
I Wizard         ... .\syncthing.exe
E StDownloader  g-io-error-quark: GET request failed: WinHttp error: SECURE_FAIL
URE (0)
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\stdownloader.py", line 135, in _cb_read_c
ompatibility
Error: g-io-error-quark: GET request failed: WinHttp error: SECURE_FAILURE (0)
^C
```
if I download daemon and put it in the required folder, daemon version error appears. daemon last stable version
```
c:\Program Files\SyncthingGTK>syncthing-gtk-console.exe
I StatusIcon    Using backend StatusIconGTK3 (primary)
I Wizard        Searching for syncthing binary...
I Wizard         ... ./syncthing.exe
I Wizard         ... C:\Documents and Settings\admin/.local/bin\syncthing.exe
I Wizard         ... C:\Documents and Settings\admin\Local Settings\Application
Data\syncthing\syncthing.exe
I Wizard        Binary found in C:\Documents and Settings\admin\Local Settings\A
pplication Data\syncthing\syncthing.exe
I Wizard        Binary in C:\Documents and Settings\admin\Local Settings\Applica
tion Data\syncthing\syncthing.exe is too old
I Wizard         ... c:/Program Files/syncthing\syncthing.exe
I Wizard         ... c:/Program Files (x86)/syncthing\syncthing.exe
I Wizard         ... C:\Documents and Settings\admin\Local Settings\Application
Data\syncthing\syncthing.exe
I Wizard        Binary found in C:\Documents and Settings\admin\Local Settings\A
pplication Data\syncthing\syncthing.exe
I Wizard        Binary in C:\Documents and Settings\admin\Local Settings\Applica
tion Data\syncthing\syncthing.exe is too old
I Wizard         ... .\syncthing.exe
E StDownloader  g-io-error-quark: GET request failed: WinHttp error: SECURE_FAIL
URE (0)
Traceback (most recent call last):
  File "C:\syncthing-gtk\syncthing_gtk\stdownloader.py", line 135, in _cb_read_c
ompatibility
Error: g-io-error-quark: GET request failed: WinHttp error: SECURE_FAILURE (0)
^C
```

**Comment by kozec** [comment]
Ok, where in the world have you found Winserver 2003? :)

> if I download daemon and put it in the required folder, daemon version error appears. daemon last stable version

What exact version you are downloading? Current ST-GTK should work with Syncthing 0.14 or later. You can then disable autoupdate from settings or with registry in `HKEY_CURRENT_USERS/Software/SyncthingGTK`, set `st_autoupdate` to 0.

**Comment by SofroN** [comment]
unfortunately I have to work with him. :-(
latest version 0.14.45 
disabling auto-update did not help.
PS. it's first run, with wizard

**Comment by kozec** [comment]
Ok, assuming W2003 has same issues as XP, wizard probably should not be starting there. I can add  detection later, but for you, just starting syncthing binary and letting it run for while should create required syncthing configuration and prevent wizard from starting.

**Comment by SofroN** [comment]
Please get sample config file

**Comment by kozec** [comment]
> Please get sample config file

Sorry, but I don't understand what you are saying.
