### ISSUE TITLE
Syncthing-gtk no longer works on one ubuntu 16.04 machine, but works on another…

### ISSUE THREAD

**Issue by Coeur-Noir** [syncthing/syncthing-gtk#443]
Hi,
well probably not a real bug but something related to my machine ?
![capture du 2018-03-31 13-19-58](https://user-images.githubusercontent.com/1895947/38162829-d3ed350c-34e8-11e8-91b7-0ef61027190e.png)
It seems broken on a 16.04 system installed from zero, but works as exepected on a 16.04 system upgraded from previous 14.04 installation.

```
gdpalace@Asgard:~$ syncthing-gtk -d
D UIBuilder     Enabled: traditional_header
D UIBuilder     Enabled: icons_in_menu
D UIBuilder     Loading glade file /usr/share/syncthing-gtk/app.glade
D UIBuilder     Enabled conditions: set([u'icons_in_menu', u'traditional_header'])
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node !is_gnome | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: old_gtk
D UIBuilder     Removed 'child' by attribute: header_bar
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'child' by attribute: is_windows
D UIBuilder     Allowed node icons_in_menu | old_gtk
D UIBuilder     Removed 'property' by attribute: is_windows
D UIBuilder     Allowed node traditional_header
D UIBuilder     Allowed node traditional_header | icons_in_menu
/usr/lib/python2.7/dist-packages/syncthing_gtk/statusicon.py:453: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
W StatusIcon    StatusIcon: Using backend StatusIconAppIndicator (fallback)
D Daemon        Reading syncthing config /home/gdpalace/.config/syncthing/config.xml
V Notifications Error notifications enabled
V Notifications File update notifications enabled
V Daemon        Set refresh interval to 1

(syncthing-gtk:6924): Gtk-WARNING **: Invalid icon size 16

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 398, in _request_config
    RESTRequest(self, "system/config", self._syncthing_cb_config, self._syncthing_cb_config_error).start()
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 1045, in __init__
    self.connect("event", self._socket_event)
TypeError: argument connectable: Expected Gio.SocketConnectable, but got unicode

(syncthing-gtk:6924): Gtk-WARNING **: Invalid icon size 16


(syncthing-gtk:6924): Gtk-WARNING **: Invalid icon size 16


(syncthing-gtk:6924): Gtk-WARNING **: Invalid icon size 16
```
Where it seems broken, integration with Nautilus is also out of order ( no« sync-state-labels » on icons ).

Hopefully Syncthing itself is still working on the 3 concerned machines.

**Comment by kozec** [comment]
This happens when older ST-GTK gets started with too new gtk library. Can you check if upgrading ST-GTK is possible?

**Comment by Coeur-Noir** [comment]
I've just noticed webupd8 ppa is no longer mentioned but opensuse build service instead - which responds with a 503 error for now.
![capture du 2018-04-01 14-49-03](https://user-images.githubusercontent.com/1895947/38173282-e74be2dc-35bb-11e8-892f-a725f3c8bb50.png)

Should I try the AppImage ? Should I uninstall first my actual version and stop using webupd8's ppa ?

**Comment by kozec** [comment]
OBS should be alive again. Sorry, I can't really do much there.

> Should I uninstall first my actual version and stop using webupd8's ppa ?

You should be able to upgrade normally. webupd8 ppa is fine, OBS just should be updated faster.
