### ISSUE TITLE
Error: libffi.so.4: cannot open shared object file (AppImage)

### ISSUE THREAD

**Issue by rkdnc** [syncthing/syncthing-gtk#456]
Attempting to install via AppImage on Ubuntu (18.04), ran as instructed on the AppImage website ( `$ chmod a+x .AppImage`) only to be greeted by this error:

```I StatusIcon    Using backend StatusIconGTK3 (primary)

Traceback (most recent call last):

  File "/tmp/.mount_SyncthSKiTMK/usr/lib/python2.7/site-packages/syncthing_gtk/app.py", line 220, in do_command_line

    if self.setup_connection():

  File "/tmp/.mount_SyncthSKiTMK/usr/lib/python2.7/site-packages/syncthing_gtk/app.py", line 371, in setup_connection

    self.show_wizard()

  File "/tmp/.mount_SyncthSKiTMK/usr/lib/python2.7/site-packages/syncthing_gtk/app.py", line 420, in show_wizard

    from syncthing_gtk.wizard import Wizard

  File "/tmp/.mount_SyncthSKiTMK/usr/lib/python2.7/site-packages/syncthing_gtk/wizard.py", line 18, in <module>

    import os, socket, random, string, bcrypt

  File "/tmp/.mount_SyncthSKiTMK/usr/lib64/python2.7/site-packages/bcrypt/__init__.py", line 23, in <module>

    from bcrypt import _bcrypt

ImportError: libffi.so.4: cannot open shared object file: No such file or directory

W StatusIcon    StatusIcon: Using backend StatusIconDummy (fallback)
```

**Comment by oecherjong** [comment]
I have the same problem with Xubuntu 17.10 (Artful Aardvark).
How do I get version 4 of libiffi into the game? Version 6 is already installed.

**Comment by kozec** [comment]
With above fix, it should work in next release.
