### ISSUE TITLE
syncthing-gtk requires libnotify-dev on Ubuntu 16.04

### ISSUE THREAD

**Issue by cryobry** [syncthing/syncthing-gtk#457]
```
$ syncthing-gtk
Traceback (most recent call last):
  File "/usr/bin/syncthing-gtk", line 37, in <module>
    from syncthing_gtk.app import App
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 17, in <module>
    from syncthing_gtk.notifications import Notifications, HAS_DESKTOP_NOTIFY
  File "/usr/lib/python2.7/dist-packages/syncthing_gtk/notifications.py", line 19, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

After installing libnotify-dev, syncthing-gtk runs as expected.

Ubuntu 16.04

**Comment by kozec** [comment]
It's listed as dependency in readme. Where are you installing it from?

**Comment by cryobry** [comment]
```
$ cat /etc/apt/sources.list.d/home\:kozec.list 
deb http://download.opensuse.org/repositories/home:/kozec/xUbuntu_16.04/ /
```

**Comment by kozec** [comment]
Ah. Of course _I_ am the one who haven't read README...

It should be fixed when OBS finishes rebuilding.
