### ISSUE TITLE
Syncthing-GTK appimage fails to run, GTK3 missing

### ISSUE THREAD

**Issue by dyedquartz** [syncthing/syncthing-gtk#509]
Running Debian 9 on KDE.
```
$ ./SyncthingGTK-0.9.4.3-x86_64.AppImage 

** (process:25764): WARNING **: 10:44:13.415: Failed to load shared library 'libgdk-3.so.0' referenced by the typelib: libjpeg.so.8: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.mount_SyncthQjozzG/usr/lib/python2.7/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/.mount_SyncthQjozzG/usr/lib/python2.7/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/tmp/.mount_SyncthQjozzG/usr/lib/python2.7/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/.mount_SyncthQjozzG/usr/lib/python2.7/site-packages/gi/overrides/Gdk.py", line 81, in <module>
    Color = override(Color)
  File "/tmp/.mount_SyncthQjozzG/usr/lib/python2.7/site-packages/gi/overrides/__init__.py", line 202, in override
    assert g_type != TYPE_NONE
AssertionError
Syncthing-GTK requires GTK and gobject-introspection packages.\n Please, install GTK3 and gobject-introspection packages using your package manager
/usr/bin/zenity: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
```

**Comment by catb0t** [comment]
have you tried installing the dependencies?

**Comment by dyedquartz** [comment]
I have tried, but I don't know if I have gotten all of the required dependencies. I have tried installing `gobject-introspection` and `libgtk-3-0` which the latter has already been installed.

**Comment by dyedquartz** [comment]
UPDATE: I installed all of the dependencies, but the installer still does not want to launch

**Comment by kozec** [comment]
AppImage is entire application, not installer. But what you are describing shouldn't be happening and is most likely related to that libjpeg message. I can try bundling libjpeg along with everything else, but in meantime, it may be simpler to get deb package from [obs](https://software.opensuse.org/download.html?project=home%3Akozec&package=syncthing-gtk).

**Comment by dyedquartz** [comment]
Thanks, that has worked for me installing syncthing-gtk, but now it does not show the folders on the left side, none at all.

**Comment by kozec** [comment]
Try starting it from terminal (`syncthing-gtk -d -v`) and check if it displays any errors.

**Comment by dyedquartz** [comment]
https://gist.github.com/dyedquartz/e0527d2c2b32bc0d79f12271224e6e97

Log

**Comment by kozec** [comment]
> `KeyError: u'fsWatcherEnabled'`

Sounds like really old version of syncthing.

**Comment by dyedquartz** [comment]
ok, I'm going to try to install the most updated version of syncthing, and see if that fixes it

**Comment by dyedquartz** [comment]
Alright, Downloading the newest binary thought the gtk app worked, thanks for all the help!

**Comment by charlag** [comment]
For the people experiencing this in the future: tried to run AppImage on Fedora, had packages but still had this error, trying to install from the repos now and it pulls these things:

```
 python2-gobject                                            x86_64                                       3.32.2-1.fc30                                        updates                                        16 k
 python2-gobject-base                                       x86_64                                       3.32.2-1.fc30                                        updates                                       312 k
 python2-bcrypt                                             x86_64                                       3.1.4-7.fc30                                         fedora                                         40 k
 python2-dateutil  
```

so that's likely what you need?
