### ISSUE TITLE
Crash: infobox.py line 528, in set_value TypeError: Must be string, not bool

### ISSUE THREAD

**Issue by jjakob** [syncthing/syncthing-gtk#518]
When adding a shared folder.

excerpt from apport crash log:
```
Traceback:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 1161, in _response
     self._callback(rdata, *self._callback_data)
   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 893, in run_before
     callback(*calbackdata)
   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/editordialog.py", line 448, in syncthing_cb_post_config
     self.on_saved()
   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/foldereditor.py", line 232, in on_saved
     key=lambda x : x.get_title().lower()
   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/app.py", line 1407, in show_folder
     box.add_hidden_value("folder_type", folder_type)
   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/infobox.py", line 519, in add_hidden_value
     self.set_value(key, value)
   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/infobox.py", line 528, in set_value
     self.value_widgets[key][0].set_text(value)
 TypeError: Must be string, not bool

ApportVersion: 2.20.1-0ubuntu2.19
Architecture: amd64
DistroRelease: Ubuntu 16.04
```

**Comment by jjakob** [comment]
Correction, this happens when first adding a folder sent (shared) from a different device. To reproduce, share a folder from a different device to this one, give it a name and path, enable "Monitor filesystem for changes" and save. At this point it crashes. Crash happens always, 100%.
