### ISSUE TITLE
Synthing appImage fails with errors on Linux Mint

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing-gtk#531]
```
$ ./SyncthingGTK-0.9.4.4-x86_64.AppImage
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.mount_SyncthsSd05w/usr/lib/python2.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_SyncthsSd05w/usr/lib/libglib-2.0.so.0)
Syncthing-GTK requires GTK and gobject-introspection packages.\n Please, install GTK3 and gobject-introspection packages using your package manager
/usr/bin/zenity: error while loading shared libraries: libicuuc.so.64: cannot open shared object file: No such file or directory

```

OS: Linux Mint 19.2 Tina x86_64 
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.2.17-050217-generic 
Uptime: 1 hour, 4 mins 
Packages: 3121 (dpkg), 6 (flatpak), 4 (snap) 
Shell: bash 4.4.20 
Resolution: 2560x1440 @ 60.01Hz 
DE: Cinnamon 4.2.4 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark-trans (Mint-Y-Dark-BB_hack) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: InconsolataGo 12 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 
Memory: 2299MiB / 15931MiB 
Disk (/dev/nvme0n1p4): 18G / 40G (47%) 
Disk (/dev/nvme0n1p2): 232G / 405G (61%) 
Disk (udev): 0 / 7.8G (0%)

**Comment by LinuxOnTheDesktop** [comment]
Cf. #462, which was 'closed due to age' - and opened in July last year. I note that a main point of AppImage's is to _avoid_ exactly this sort of dependency problem.

**Comment by kozec** [comment]
#462 was actually fixed by d0833fdc13c0bda5b59b32ef0fb04220db4c6be1.

glibc is exception even for appimage and can't be bundled, AFAIK. 2.28 is already pretty archaic, what version is used by Mint?

**Comment by LinuxOnTheDesktop** [comment]
2.27, judging by this:

```
testing@testing-VirtualBox:~$ apt list glibc*
Listing... Done
glibc-doc/bionic,bionic 2.27-3ubuntu1 all
glibc-doc-reference/bionic,bionic 2.27-1 all
glibc-source/bionic,bionic 2.27-3ubuntu1 all
```

**Comment by Morganlej** [comment]
The part 
  libicuuc.so.64: cannot open shared object file: No such file or directory
also occurs on Mageia 7, which use version 63.
I think libicuuc.so.64 should be bundled too in the appimage?

https://bugs.mageia.org/show_bug.cgi?id=22811
