### ISSUE TITLE
Nautilus plugin fills up journal "Could not connect to 127.0.0.1: Connection refused"

### ISSUE THREAD

**Issue by TechupBusiness** [syncthing/syncthing-gtk#537]
When I stop the syncthing-gtk I get such an entry every second in my journal (`journalctl -f`):
```
Okt 21 19:46:47 techup nautilus-autostart.desktop[3360]: E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Okt 21 19:46:47 techup nautilus-autostart.desktop[3360]: Traceback (most recent call last):
Okt 21 19:46:47 techup nautilus-autostart.desktop[3360]:   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 1052, in _connected
Okt 21 19:46:47 techup nautilus-autostart.desktop[3360]:     self._connection = self.connect_to_service_finish(results)
Okt 21 19:46:47 techup nautilus-autostart.desktop[3360]: Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Okt 21 19:46:47 techup org.gnome.Nautilus[2994]: E Daemon        g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
Okt 21 19:46:47 techup org.gnome.Nautilus[2994]: Traceback (most recent call last):
Okt 21 19:46:47 techup org.gnome.Nautilus[2994]:   File "/usr/lib/python2.7/dist-packages/syncthing_gtk/daemon.py", line 1052, in _connected
Okt 21 19:46:47 techup org.gnome.Nautilus[2994]:     self._connection = self.connect_to_service_finish(results)
Okt 21 19:46:47 techup org.gnome.Nautilus[2994]: Error: g-io-error-quark: Could not connect to 127.0.0.1: Connection refused (39)
```

**Comment by kozec** [comment]
That looks like normal output while plugin is connecting. Check what's pumping stderr from nautilus to your journal and disable it.

**Comment by TechupBusiness** [comment]
Hm. So there is no option/need to optimize it? Running every second 2 connection attempts is a normal and acceptable behavior?

**Comment by kozec** [comment]
I don't think so, waiting for connection and sleeping after it fails should not take any resources at all.
