### ISSUE TITLE
AppImage (latest) doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by jvalrog** [syncthing/syncthing-gtk#550]
Can't get the AppImage to work:

```
$ chmod +x SyncthingGTK-0.9.4.4-x86_64.AppImage 
$ ./SyncthingGTK-0.9.4.4-x86_64.AppImage 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.mount_SyncthArQQ70/usr/lib/python2.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_SyncthArQQ70/usr/lib/libglib-2.0.so.0)
Syncthing-GTK requires GTK and gobject-introspection packages.\n Please, install GTK3 and gobject-introspection packages using your package manager
/usr/bin/zenity: error while loading shared libraries: libicuuc.so.64: cannot open shared object file: No such file or directory
```

It says to install something on my system, but I suppose AppImage is about not installing anything, right?

**Comment by asyassa** [comment]
Seeing same problem. Ubuntu 16.04. Any solutions?

**Comment by kozec** [comment]
Main idea was to not bundle libraries that are usually installed everywhere, but that's probably not true anymore. I'll try to repack it with everything, but I have to ask you for patience as this is very much trial-error-repeast process.

**Comment by freaky-m0** [comment]
Same here with the latest Linux Mint. Sure because it's 18.04 based.

Would be nice to bundle glibc as you said. Thanks in advance!

**Comment by kozec** [comment]
This is not yet fully working, as it can't download syncthing daemon during "1st run wizard", but it should work with syncthing already installed / downloaded.

[Syncthing_GTK-with-everything.x86_64.AppImage](https://github.com/kozec/syncthing-gtk/releases/download/appimage-with-everything/Syncthing_GTK-with-everything.x86_64.AppImage)

Can someone confirm it works on those Ubuntu/Mint installations?

**Comment by JmmyGun** [comment]
On  Mint 19.3

Traceback (most recent call last):
  File "/tmp/.mount_Syncth3azsz6/usr/bin/syncthing-gtk", line 19, in <module>
    gi.require_version('Rsvg', '2.0')
  File "/tmp/.mount_Syncth3azsz6/usr/lib/python2.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available

**Comment by muelli** [comment]
You can try the flatpaked version. It should work quite well.

**Comment by JmmyGun** [comment]
yes flapaked version, work well thx.

**Comment by freaky-m0** [comment]
Same problem with my Mint 19.3 installation. I'll try the flatpak version. As I remember it wasn't updated a while ago? Am I right?

**Comment by wigy-opensource-developer** [comment]
Ubuntu Mate 19.10 (Eoan Ermine) here (gtk3 is not preinstalled on this distro). The regular release was missing GTK3, the "with everything" is still missing 

```sh
$ ./Syncthing_GTK-with-everything.x86_64.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_Syncthv0LwYQ/usr/bin/syncthing-gtk", line 19, in <module>
    gi.require_version('Rsvg', '2.0')
  File "/tmp/.mount_Syncthv0LwYQ/usr/lib/python2.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available
```

A search for available packages shows the following:

```sh
$ apt search Rsvg
Sorting... Done
Full Text Search... Done
gir1.2-rsvg-2.0/eoan 2.44.14-1 amd64
  gir files for renderer library for SVG files

[...]

librsvg2-2/eoan,now 2.44.14-1 amd64 [installed,automatic]
  SAX-based renderer library for SVG files (runtime)

librsvg2-bin/eoan 2.44.14-1 amd64
  command-line utility to convert SVG files

librsvg2-common/eoan,now 2.44.14-1 amd64 [installed,automatic]
  SAX-based renderer library for SVG files (extra runtime)

librsvg2-dev/eoan 2.44.14-1 amd64
  SAX-based renderer library for SVG files (development)

[...]
```

Installing packages `gir1.2-rsvg-2.0` and `librsvg2-bin` did not help.
