### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by rndmh3ro** [syncthing/syncthing-gtk#70]
Right after starting syncthing-gtk throws the following exception. However there seems to be no issue using syncthing. Everything seems to work.
```
Syncthing-GTK started and running in notification area
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 457, in _rest_response
    callback(rdata)
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/daemon.py", line 672, in _init_event_pooling
    self._last_error_time = parsetime(events[-1]["time"])
  File "/usr/lib/python2.7/site-packages/syncthing_gtk/tools.py", line 149, in parsetime
    times = list(match.groups()[0:3])
AttributeError: 'NoneType' object has no attribute 'groups'
```

System:
Linux archlinux 3.18.2-2-ARCH #1 SMP PREEMPT Fri Jan 9 07:37:51 CET 2015 x86_64 GNU/Linux

syncthing version: syncthing-gtk-0.5.7-1

**Comment by kozec** [comment]
Sounds like time format in `/rest/events` response is not right. Could you, please, open `<webui_ip:port>/rest/events` in your browser and copy-paste few lines?
Also, version of Syncthing daemon (last line in top-right box)  would help.
