### ISSUE TITLE
watcher.py: UnicodeDecodeError

### ISSUE THREAD

**Issue by akhayyat** [syncthing/syncthing-gtk#93]
This appears to originate from the call:
```python
self.wm.add_watch(path,
    pyinotify.IN_CLOSE_WRITE | pyinotify.IN_MOVED_TO | pyinotify.IN_MOVED_FROM |
    pyinotify.IN_DELETE | pyinotify.IN_CREATE, rec=True
)
```
in the `watcher.py` file in the `WatcherCls.watch()` method.

Because it adds paths recursively, I'm not even sure how to pinpoint the specific offending path.

Note: syncthing-inotify appears to handle the same folder just fine.

Here is the syncthing-gtk traceback:
```python
Traceback (most recent call last):
  File "<...>/syncthing-gtk/syncthing_gtk/app.py", line 859, in cb_syncthing_folder_added
    self.watcher.watch(box["norm_path"])
  File "<...>/syncthing-gtk/syncthing_gtk/watcher.py", line 39, in watch
    pyinotify.IN_DELETE | pyinotify.IN_CREATE, rec=True
  File "/usr/lib/python2.7/dist-packages/pyinotify.py", line 1898, in add_watch
    for rpath in self.__walk_rec(apath, rec):
  File "/usr/lib/python2.7/dist-packages/pyinotify.py", line 2082, in __walk_rec
    for root, dirs, files in os.walk(top):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 1: ordinal not in range(128
```

**Comment by kozec** [comment]
I'm afraid that this may be even bug in pyinotify, code would crash much earlier if wrong string were passed by ST-GTK :( Can you give me example of some non-latin looking directory there? Knowing what locale are you using would help as well.

**Comment by akhayyat** [comment]
I'm using the en_US.UTF-8 locale. There are folders with Arabic names. However, running:

    python -m pyinotify <folder-name>

does not raise any errors, even when browsing the Arabic-named folders and causing some inotify events in them.

**Comment by AudriusButkevicius** [comment]
I think: box["norm_path"] might be unicode and not utf-8, which could be the issue?

**Comment by kozec** [comment]
> I think box["norm_path"] might be unicode and not utf-8, which could be the issue?

Yes, but I still don't understand why would it crash only of subfolder and only for Arabic (and not for mine diacritical marks). Anyway, I'm getting some Arabic for testing right now :D
